apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "audity.fullname" . }}-api
  labels:
    {{- include "audity.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.api.minAvailable }}
  selector:
    matchLabels:
      {{- include "audity.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "audity.fullname" . }}-worker
  labels:
    {{- include "audity.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.worker.minAvailable }}
  selector:
    matchLabels:
      {{- include "audity.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "audity.fullname" . }}-frontend
  labels:
    {{- include "audity.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.frontend.minAvailable }}
  selector:
    matchLabels:
      {{- include "audity.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
